{% set version = "1.3.1" %}
{% set patch_version = "3" %}

package:
  name: cutensor
  version: {{ version }}.{{ patch_version }}

source:
  url: https://developer.download.nvidia.com/compute/cutensor/{{ version }}/local_installers/libcutensor-linux-x86_64-{{ version }}.{{ patch_version }}.tar.gz   # [linux64 and cuda_compiler_version in ("10.1", "10.2", "11.0")]
  url: https://developer.download.nvidia.com/compute/cutensor/{{ version }}/local_installers/libcutensor-linux-ppc64le-{{ version }}.{{ patch_version }}.tar.gz  # [ppc64le and cuda_compiler_version in ("10.1", "10.2", "11.0")]
  # url: https://developer.download.nvidia.com/compute/cutensor/{{ version }}/local_installers/libcutensor-linux-sbsa-{{ version }}.{{ patch_version }}.tar.gz  # [aarch64 and cuda_compiler_version in ("10.1", "10.2", "11.0")]
  url: https://developer.download.nvidia.com/compute/cutensor/{{ version }}/local_installers/libcutensor-windows-x86_64-{{ version }}.{{ patch_version }}.zip  # [win64 and cuda_compiler_version in ("10.1", "10.2", "11.0")]

  sha256: 98d9559da6c1d880b71e7618d266f4e912ea4330f137d78f195781cb7864042f  # [linux64]
  sha256: 1621f950b91929abf05ab581b16a71285370523540d7be3fdf6fc1259e44f6ac  # [ppc64le]
  # sha256: 031b75946d2ce22f8c2736f7b4216b9377406afcb35012093a66e2801bfe2990  # [aarch64]
  sha256: faec7c8c5783fa7e06d5ec41c9372dee3f9a14d155038539a6bf52a6ce31f25e  # [win64]

build:
  number: 0
  # cuTENSOR v1.3.1 supports CUDA 10.2, 11.0, and 11.1+
  skip: True  # [win32 or cuda_compiler_version not in ("10.2", "11.0", "11.1")]
  script_env:
    # for some reason /usr/local/cuda is not added to $PATH in ppc64le's docker image
    - CUDA_HOME  # [ppc64le]
  script:
    - mkdir -p $PREFIX/include                                            # [linux]
    - cp -r include/* $PREFIX/include/                                    # [linux]
    - mkdir -p $PREFIX/lib                                                # [linux]
    - mv lib/{{ cuda_compiler_version }}/libcutensor.so* $PREFIX/lib/     # [linux and cuda_compiler_version in ("10.2", "11.0")]
    - mv lib/11/libcutensor.so* $PREFIX/lib/                              # [linux and cuda_compiler_version == "11.1"]

    - copy include\\cutensor.h %LIBRARY_INC%\\                             # [win64]
    - mkdir %LIBRARY_INC%\\cutensor                                        # [win64]
    - copy include\\cutensor\\types.h %LIBRARY_INC%\\cutensor              # [win64]
    - copy lib\\{{ cuda_compiler_version }}\\cutensor.dll %LIBRARY_BIN%\\  # [win64 and cuda_compiler_version in ("10.2", "11.0")]
    - copy lib\\{{ cuda_compiler_version }}\\cutensor.lib %LIBRARY_LIB%\\  # [win64 and cuda_compiler_version in ("10.2", "11.0")]
    - copy lib\\11\\cutensor.dll %LIBRARY_BIN%\\                           # [win64 and cuda_compiler_version in ("11.1", )]
    - copy lib\\11\\cutensor.lib %LIBRARY_LIB%\\                           # [win64 and cuda_compiler_version in ("11.1", )]
  ignore_run_exports_from:
    - {{ compiler('c') }}    # [linux]
    - {{ compiler('cuda') }}
  run_exports:
    - {{ pin_subpackage('cutensor') }}
  missing_dso_whitelist:
    - '*/libgomp.*'  # [linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cuda') }}
    - sysroot_linux-64 2.17  # [linux]
    - libgomp  # [linux]
  host:
  run:
    # Only GCC_3.0 or older symbols present
    - libgcc-ng >=3.0     # [linux]
    # Only GLIBCXX_3.4 or older symbols present
    - libstdcxx-ng >=3.4  # [linux]
    - cudatoolkit {{ cuda_compiler_version }}  # [cuda_compiler_version in ("10.2", "11.0")]
    - cudatoolkit >=11.1                       # [cuda_compiler_version == "11.1"]
  run_constrained:
    # Only GLIBC_2.17 or older symbols present
    - __glibc >=2.17      # [linux]

test:
  requires:
    - git
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - sysroot_linux-64 2.17  # [linux]
    # make sure we pick up the version matching the docker,
    # or the linker would complain 
    - cudatoolkit {{ cuda_compiler_version }}
  commands:
    - test -f $PREFIX/include/cutensor.h                    # [linux]
    - test -f $PREFIX/include/cutensor/types.h              # [linux]
    - test -f $PREFIX/lib/libcutensor.so                    # [linux]

    - if not exist %LIBRARY_INC%\\cutensor.h exit 1         # [win64]
    - if not exist %LIBRARY_INC%\\cutensor\\types.h exit 1  # [win64]
    - if not exist %LIBRARY_BIN%\\cutensor.dll exit 1       # [win64]
    - if not exist %LIBRARY_LIB%\\cutensor.lib exit 1       # [win64]

about:
  home: https://developer.nvidia.com/cutensor
  license: LicenseRef-cuTENSOR-Software-License-Agreement
  license_url: https://docs.nvidia.com/cuda/cutensor/license.html
  license_file: license.txt
  summary: "Tensor Linear Algebra on NVIDIA GPUs"
  description: |
    The cuTENSOR Library is a first-of-its-kind GPU-accelerated tensor linear
    algebra library providing tensor contraction, reduction and elementwise
    operations. cuTENSOR is used to accelerate applications in the areas of
    deep learning training and inference, computer vision, quantum chemistry
    and computational physics.

    License Agreements:- The packages are governed by the NVIDIA cuTENSOR
    Software License Agreement (EULA). By downloading and using the packages,
    you accept the terms and conditions of the NVIDIA cuTENSOR EULA -
    https://docs.nvidia.com/cuda/cutensor/license.html
  doc_url: https://docs.nvidia.com/cuda/cutensor/index.html
  dev_url: https://developer.nvidia.com/cutensor/downloads

extra:
  recipe-maintainers:
    - leofang
    - jakirkham
